### ISSUE TITLE
[w2-pandas-project] JAIME MUÑOZ 

### ISSUE THREAD

**Issue by JIMYTHEONE** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#1]

**Comment by JIMYTHEONE** [comment]
[w2-pandas-project](https://github.com/Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project)

**Comment by JIMYTHEONE** [comment]
https://github.com/JIMYTHEONE/SHARKS-JAIME.git

**Comment by AdrianCiges** [comment]
Muy buen trabajo en la limpieza. El repo lo tienes que mejorar. Organiza mejor los archivos por carpetas: Una para el código (src por convención), una para Data, imágenes (si tuvieras), etc. El readme tiene que ser la carta de presentación de tu repo. Cuando un recuiter entre en tu github a ojear algún proyecto lo primero que mirará será tu readme para ver qué has hecho y qué sabes manejar. Dale importancia, ponlo bonito y sé explicativo (pero directo).
Muy bien comentado el código en el notebook. Bien justificadas las decisiones. Sigue así!
