### ISSUE TITLE
[w2-pandas-proyect] Víctor

### ISSUE THREAD

**Issue by victorrmtz** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#11]
https://github.com/victorrmtz/Proyecto-Shark-Limpieza-.git

**Comment by AdrianCiges** [comment]
Muy buen trabajo!!
Por apuntar cositas, el readme extiéndelo un poco más para las próximas (evita poner código) y la carpeta de código llámala src (por convención) y, ya que vas genial (BONUS PERSONALIZADO!), chequea como hacer las limpiezas con menos elif. Ojea como funciona find 👀
Muy buenas prácticas guardar un .py con funciones!
Perfect Víctor, muy muy bien.
