### ISSUE TITLE
[ w2-pandas-project] Pablo Galán

### ISSUE THREAD

**Issue by pablogalann** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#15]
https://github.com/pablogalann/Proyecto-Sharks.git

**Comment by AdrianCiges** [comment]
Buen trabajo de limpieza.
Ojo con los outputs muy largos, nos revientan el scroll. Coméntalos cuando ya hayas visualizado lo que quieres.
El readme bien explicado, pero intenta que sea más visual. Algún emoji, explicaciones más directas, etc.
Organiza el repo por carpetas, una para el código (src por conveción), imágenes si tuvieras, etc.
Sigue así!
