### ISSUE TITLE
Project Shark Sergio

### ISSUE THREAD

**Issue by SergioSuarezgh** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#19]
https://github.com/SergioSuarezgh/BabyShark_Sergio.git

**Comment by AdrianCiges** [comment]
Muy buen trabajo!
Cuidado con los outputs largos, nos revientan el scroll! Coméntalos una vez los hayas visualizado porfa.
Organiza el repo por carpetas. Usa scr para guardar los notebooks con el código, img para las imágenes.
El readme genial, esa es la idea.
Brutal que te hayas creado un .py con las funciones. Muy buena práctica.
Muy buen camino Sergio. Sigue así!
