### ISSUE TITLE
Sharks-Proyecto-28.10.2022 Pablo Garcia Berdoy

### ISSUE THREAD

**Issue by pgb314** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#2]
https://github.com/pgb314/Sharks-Proyecto-28.10.2022.git

**Comment by AdrianCiges** [comment]
Poco más que añadir a lo dicho por slack, insistir en que no pongas el código en el readme. 
Muy buen curro de limpieza, usando regex y todo. Maravilla.
