### ISSUE TITLE
[w2-pandas-project] María Miño

### ISSUE THREAD

**Issue by mariamino** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#24]
https://github.com/mariamino/data-cleaning-pandas.git

**Comment by AdrianCiges** [comment]
Poco más que añadir a lo que te hemos dicho por slack. Está muy bien, el readme muy cuidado (usa algún emoji para la próxima, están de moda, poca broma). Muy buen trabajo, sigue así :)
