### ISSUE TITLE
[SHARKS] Silvia Barge

### ISSUE THREAD

**Issue by Barge7** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#3]

**Comment by AdrianCiges** [comment]
Nos falta el link a tu repo!

**Comment by Barge7** [comment]
Perdonad!!! es esto? https://github.com/Barge7/SHARK

**Comment by AdrianCiges** [comment]
Buen trabajo de limpieza. Podrías haber profundizado más en algunas columnas, pero está muy bien con el tiempo que teníais. 
El repo intenta organizarlo por carpetas. Usa una llamada src (por convención) para tu código. 
El ppt se puede pulir pero lo mismo, con el poco tiempo que habéis tenido está muy bien. Es un buen ejemplo de lo que se llama "producto mínimo viable". Has sacado algo cerrado en poco tiempo. Buen trabajo, sigue así!
