### ISSUE TITLE
[ w2-pandas-project]Julia Sabatel

### ISSUE THREAD

**Issue by juliasabatel** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#6]
https://github.com/juliasabatel/Sharks_proyecto

**Comment by AdrianCiges** [comment]
Buen trabajo en la limpieza, has sido minuciosa en muchas columnas pero podrías haber profundizado más en otras. Con el tiempo que teníais se entiendes, así que don't worry, está genial. 
El repo lo tienes que mejorar. Organiza mejor los archivos por carpetas: Una para el código (src por convención), una para Data, Imágenes (si tuvieras), etc. 
El readme tiene que ser la carta de presentación de tu repo. Cuando un recuiter entre en tu github a ojear algún proyecto lo primero que mirará será tu readme para ver qué has hecho y qué sabes manejar. Lo has cuidado, está genial, pero intenta ser un pelín (solo un pelín) más explicativa la próxima y siempre SIEMPRE evita poner código en el readme. 
Los gráficos pueden mejorarse, pero tendremos días donde profundizaremos en la visualización, así que paso a paso.
Muy bien comentado el código en el notebook. Buen trabajo en general!
