### ISSUE TITLE
[w2-pandas-project] Nony

### ISSUE THREAD

**Issue by jquintanac** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#7]
https://github.com/Nonyto/PROY-SHARK-NONY

**Comment by AdrianCiges** [comment]
Buen trabajo, pero podría haber profundizado mucho más en la limpieza.
Muy bien organizado el repo, con sus carpetas para cada cosa. Genial! Por convención, la carpeta de código se suele llamar src.
El readme, EL README! Tiene que ser la carta de presentación de tu repo. Cuando un recuiter entre en tu github a ojear algún proyecto lo primero que mirará será tu readme para ver qué has hecho y qué sabes manejar. Dale importancia, ponlo bonito y sé explicativo (pero directo).
Tienes un archivo .ini en el repo que no aporta nada. Corrígeme si me equivoco, pero lo eliminaría.
Sigue así ;)

**Comment by AdrianCiges** [comment]
Añado: La expo preciosa! Ojo con el fondo en la parte de los gráficos, que puede perderse un poco con las imágenes tan coloridas, pero muy buena expo. Ese es el camino!
