### ISSUE TITLE
[w2-pandas-poject] Rocío Moreno

### ISSUE THREAD

**Issue by rciomoreno** [Ironhack-Data-Madrid-Octubre-2022/w2-pandas-project#8]
https://github.com/rciomoreno/w2-pandas-project.git

**Comment by AdrianCiges** [comment]
Buen trabajo de limpieza. Ojo con los outputs largos! Coméntalos cuando los hayas visualizado, si no nos reviente el scroll!
El readme muy bien, usa algún emoji y gráfico para hacerlo más visual las próximas. 
Organiza el repo por carpetas. usa scr para la del código (se usa así por conveción) y mete en ella tus notebooks.
Buen trabajo!
